version: "3.8"

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api1:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - UV_THREADPOOL_SIZE=10
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    depends_on:
      db:
        condition: service_healthy

  api2:
    build: .
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - UV_THREADPOOL_SIZE=10
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:80
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
