version: "3.8"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.75"
    #       memory: "1.5GB"

  api1:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - UV_THREADPOOL_SIZE=10
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: "0.5GB"

  api2:
    build: .
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - UV_THREADPOOL_SIZE=10
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: "0.5GB"

  nginx:
    image: nginx:latest
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:80
    depends_on:
      - api1
      - api2
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: "0.5GB"
